/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StudentResultSystem;

import java.awt.Component;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.MessageFormat;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableColumn;

/**
 *
 * @author bazz1
 */
public class StudentResultSystem extends javax.swing.JFrame {

    String username = "root";
    String password = "pass123";
    String dataCon = "jdbc.mysql://localhost:127/studentresultdb";

    Connection sqlCon = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q, i;

    public StudentResultSystem() {
        initComponents();
    }

    public void uploadDB() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlCon = DriverManager.getConnection(dataCon, username, password);
            pst = sqlCon.prepareStatement("select * from studentresultdb");
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();

            q = stData.getColumnCount();
            DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
            RecordTable.setRowCount(0);
            while (rs.next()) {
                Vector columnData = new Vector();
                for (i = 1; i <= q; i++) {
                    columnData.add(rs.getString("StudentID"));
                    columnData.add(rs.getString("Firstname"));
                    columnData.add(rs.getString("Surname"));
                    columnData.add(rs.getString("Address"));
                    columnData.add(rs.getString("Gender"));
                    columnData.add(rs.getString("DOB"));
                    columnData.add(rs.getString("Mobile"));
                    columnData.add(rs.getString("Email"));

                    columnData.add(rs.getString("Course"));
                    columnData.add(rs.getString("CourseCode"));

                    columnData.add(rs.getString("Module1"));
                    columnData.add(rs.getString("Module2"));

                    columnData.add(rs.getString("Module3"));
                    columnData.add(rs.getString("Module4"));
                    columnData.add(rs.getString("Module5"));
                    columnData.add(rs.getString("Module6"));
                    columnData.add(rs.getString("Module7"));
                    columnData.add(rs.getString("Module8"));

                    columnData.add(rs.getString("Score1"));
                    columnData.add(rs.getString("Score2"));
                    columnData.add(rs.getString("Score3"));
                    columnData.add(rs.getString("Score4"));
                    columnData.add(rs.getString("Score5"));
                    columnData.add(rs.getString("Score6"));
                    columnData.add(rs.getString("Score7"));
                    columnData.add(rs.getString("Score8"));

                    columnData.add(rs.getString("TotalScore"));
                    columnData.add(rs.getString("Ranking"));
                    columnData.add(rs.getString("Date"));

                }
                RecordTable.addRow(columnData);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcboGender = new javax.swing.JComboBox<>();
        jtxtFirstname = new javax.swing.JTextField();
        jtxtStudentID = new javax.swing.JTextField();
        jtxtAddre = new javax.swing.JTextField();
        jtxtSurname = new javax.swing.JTextField();
        jtxtDOB = new javax.swing.JTextField();
        jtxtMobile = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jtxtDate = new javax.swing.JTextField();
        jtxtScore8 = new javax.swing.JTextField();
        jtxtRanking = new javax.swing.JTextField();
        jtxtScore1 = new javax.swing.JTextField();
        jtxtScore2 = new javax.swing.JTextField();
        jtxtScore3 = new javax.swing.JTextField();
        jtxtScore4 = new javax.swing.JTextField();
        jtxtScore5 = new javax.swing.JTextField();
        jtxtScore6 = new javax.swing.JTextField();
        jtxtScore7 = new javax.swing.JTextField();
        jcboModule8 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jcboModule1 = new javax.swing.JComboBox<>();
        jcboModule2 = new javax.swing.JComboBox<>();
        jcboModule3 = new javax.swing.JComboBox<>();
        jcboModule4 = new javax.swing.JComboBox<>();
        jcboModule5 = new javax.swing.JComboBox<>();
        jcboModule6 = new javax.swing.JComboBox<>();
        jcboModule7 = new javax.swing.JComboBox<>();
        jtxtTotalScore = new javax.swing.JTextField();
        jPanel55 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtTranscript = new javax.swing.JTextArea();
        jPanel66 = new javax.swing.JPanel();
        jbtnPrint = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jbtnAddNew = new javax.swing.JButton();
        jbtnResult = new javax.swing.JButton();
        jbtnTranscript = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jcboCourse = new javax.swing.JComboBox<>();
        jtxtCourseTutor = new javax.swing.JTextField();
        jtxtFacultyN = new javax.swing.JTextField();
        jtxtDeanFac = new javax.swing.JTextField();
        jtxtCourseC = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtxtProgL1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel101 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 75, 139), 8));

        jPanel1.setBackground(new java.awt.Color(230, 230, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(207, 207, 226));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 75, 139), 8));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("Email");
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setText("Student ID");
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setText("Firstname");
        jPanel10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel4.setText("Surname");
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel5.setText("Address");
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel6.setText("Gender");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel7.setText("DOB");
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel8.setText("Mobile");
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jcboGender.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jcboGender.setMaximumRowCount(8);
        jcboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Femail", "Male", "Other" }));
        jPanel10.add(jcboGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 230, 40));

        jtxtFirstname.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jPanel10.add(jtxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 230, -1));

        jtxtStudentID.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jPanel10.add(jtxtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 230, -1));

        jtxtAddre.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jPanel10.add(jtxtAddre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 230, -1));

        jtxtSurname.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jPanel10.add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 230, -1));

        jtxtDOB.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jPanel10.add(jtxtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 230, -1));

        jtxtMobile.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jPanel10.add(jtxtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 230, -1));

        jtxtEmail.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jPanel10.add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 230, -1));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 380));

        jPanel5.setBackground(new java.awt.Color(207, 207, 226));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 75, 139), 8));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel15.setText("Date");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel27.setText("Unit Select");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel28.setText("Score");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jtxtDate.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jPanel5.add(jtxtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 230, -1));

        jtxtScore8.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jtxtScore8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore8.setText("0");
        jtxtScore8.setEnabled(false);
        jtxtScore8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScore8ActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtScore8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 70, 40));

        jtxtRanking.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jPanel5.add(jtxtRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 230, -1));

        jtxtScore1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jtxtScore1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore1.setText("0");
        jtxtScore1.setEnabled(false);
        jtxtScore1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScore1ActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtScore1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 70, 40));

        jtxtScore2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jtxtScore2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore2.setText("0");
        jtxtScore2.setEnabled(false);
        jtxtScore2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScore2ActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtScore2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 70, 40));

        jtxtScore3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jtxtScore3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore3.setText("0");
        jtxtScore3.setEnabled(false);
        jtxtScore3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScore3ActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtScore3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 70, 40));

        jtxtScore4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jtxtScore4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore4.setText("0");
        jtxtScore4.setEnabled(false);
        jtxtScore4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScore4ActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtScore4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 70, 40));

        jtxtScore5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jtxtScore5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore5.setText("0");
        jtxtScore5.setEnabled(false);
        jtxtScore5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScore5ActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtScore5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 70, 40));

        jtxtScore6.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jtxtScore6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore6.setText("0");
        jtxtScore6.setEnabled(false);
        jtxtScore6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScore6ActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtScore6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 70, -1));

        jtxtScore7.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jtxtScore7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtScore7.setText("0");
        jtxtScore7.setEnabled(false);
        jtxtScore7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScore7ActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtScore7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 70, 40));

        jcboModule8.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jcboModule8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "JavaScript", "Animation", "Graphic Design", "Digital Graphic", "" }));
        jcboModule8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule8ActionPerformed(evt);
            }
        });
        jPanel5.add(jcboModule8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 230, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("1");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 30, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("2");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 30, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("3");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 30, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("4");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 30, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("5");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 30, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("6");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 30, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("7");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 30, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("8");
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 30, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel25.setText("No");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel26.setText("Total Score");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel29.setText("Ranking");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jcboModule1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jcboModule1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Visual C++ Programming", "Java Programming", "Python Programming", "C# Programming", "" }));
        jcboModule1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule1ActionPerformed(evt);
            }
        });
        jPanel5.add(jcboModule1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 230, 40));

        jcboModule2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jcboModule2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "SQL", "Database", "Spreadsheet" }));
        jcboModule2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule2ActionPerformed(evt);
            }
        });
        jPanel5.add(jcboModule2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 230, 40));

        jcboModule3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jcboModule3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "System Analysis", "Network Managment", "Information Technology" }));
        jcboModule3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule3ActionPerformed(evt);
            }
        });
        jPanel5.add(jcboModule3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 230, 40));

        jcboModule4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jcboModule4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Statistics", "Data Science", "Machine Learning", "Artificial Inteliegence" }));
        jcboModule4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule4ActionPerformed(evt);
            }
        });
        jPanel5.add(jcboModule4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 230, 40));

        jcboModule5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jcboModule5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "PHP Programming", "Computer Games Dev", "Web Site Development", "" }));
        jcboModule5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule5ActionPerformed(evt);
            }
        });
        jPanel5.add(jcboModule5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 230, 40));

        jcboModule6.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jcboModule6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Object Oriented Programming", "Software Testing", "Procedural Programming", "" }));
        jcboModule6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule6ActionPerformed(evt);
            }
        });
        jPanel5.add(jcboModule6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 230, 40));

        jcboModule7.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jcboModule7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Matplotlib", "Raspbery PI", "Cyber Security" }));
        jcboModule7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule7ActionPerformed(evt);
            }
        });
        jPanel5.add(jcboModule7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 230, 40));

        jtxtTotalScore.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jPanel5.add(jtxtTotalScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 230, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 400, 540));

        jPanel55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 75, 139), 8));
        jPanel55.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtTranscript.setBackground(new java.awt.Color(207, 207, 226));
        jtxtTranscript.setColumns(20);
        jtxtTranscript.setRows(5);
        jScrollPane1.setViewportView(jtxtTranscript);

        jPanel55.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 520));

        jPanel1.add(jPanel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 510, 540));

        jPanel66.setBackground(new java.awt.Color(207, 207, 226));
        jPanel66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 75, 139), 8));
        jPanel66.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPrint.setBackground(new java.awt.Color(95, 75, 139));
        jbtnPrint.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jbtnPrint.setForeground(new java.awt.Color(242, 242, 242));
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel66.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 120, 60));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 75, 139), 8));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("jButton1");
        jPanel8.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 140, 70));

        jButton6.setText("jButton1");
        jPanel8.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, 70));

        jPanel66.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 920, 140));

        jbtnAddNew.setBackground(new java.awt.Color(95, 75, 139));
        jbtnAddNew.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jbtnAddNew.setForeground(new java.awt.Color(242, 242, 242));
        jbtnAddNew.setText("Add");
        jbtnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddNewActionPerformed(evt);
            }
        });
        jPanel66.add(jbtnAddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 120, 60));

        jbtnResult.setBackground(new java.awt.Color(95, 75, 139));
        jbtnResult.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jbtnResult.setForeground(new java.awt.Color(242, 242, 242));
        jbtnResult.setText("Result");
        jbtnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResultActionPerformed(evt);
            }
        });
        jPanel66.add(jbtnResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 120, 60));

        jbtnTranscript.setBackground(new java.awt.Color(95, 75, 139));
        jbtnTranscript.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jbtnTranscript.setForeground(new java.awt.Color(242, 242, 242));
        jbtnTranscript.setText("Transcript");
        jbtnTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTranscriptActionPerformed(evt);
            }
        });
        jPanel66.add(jbtnTranscript, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 150, 60));

        jbtnExit.setBackground(new java.awt.Color(95, 75, 139));
        jbtnExit.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jbtnExit.setForeground(new java.awt.Color(242, 242, 242));
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel66.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 120, 60));

        jbtnReset.setBackground(new java.awt.Color(95, 75, 139));
        jbtnReset.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jbtnReset.setForeground(new java.awt.Color(242, 242, 242));
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel66.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 120, 60));

        jPanel1.add(jPanel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 920, 140));

        jPanel7.setBackground(new java.awt.Color(207, 207, 226));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 75, 139), 8));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel12.setText("Dean of Faculty");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel13.setText("Course Tutor");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel9.setText("Course");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel11.setText("Faculty Name");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel10.setText("Course Code");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jcboCourse.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jcboCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Course", "BA Animation", "BSc Computing", "BSc Computer Science", "BSc Computer Animation", "BSc Game Developer", "BSc Information System" }));
        jcboCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboCourseActionPerformed(evt);
            }
        });
        jPanel7.add(jcboCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 280, 40));

        jtxtCourseTutor.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jtxtCourseTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCourseTutorActionPerformed(evt);
            }
        });
        jPanel7.add(jtxtCourseTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 210, -1));

        jtxtFacultyN.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jPanel7.add(jtxtFacultyN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 200, -1));

        jtxtDeanFac.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jPanel7.add(jtxtDeanFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 180, -1));

        jtxtCourseC.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jPanel7.add(jtxtCourseC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 220, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel16.setText("Program Leader");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jtxtProgL1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jPanel7.add(jtxtProgL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 180, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 390, 300));

        jTabbedPane1.addTab("University Records", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(207, 207, 226));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 75, 139), 8));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel14.setText("Student Result Managment System");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1310, 120));

        jPanel101.setBackground(new java.awt.Color(207, 207, 226));
        jPanel101.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 75, 139), 8));
        jPanel101.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Firstname", "Surname", "Address", "Gender", "DOB", "Mobile", "Email", "Course", "CourseCode", "Module 1", "Module 2", "Module 3", "Module 3", "Module 5", "Module 6", "Module 7", "Module 8", "Score 1", "Score 2", "Score 3", "Score 4", "Score 5", "Score 6", "Score 7", "Score 8", "TotalScore", "Ranking", "Date"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable1);

        jPanel101.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1290, -1));

        jPanel2.add(jPanel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1310, 560));

        jTabbedPane1.addTab("Student Record", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1350, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResultActionPerformed
        // TODO add your handling code here:
        int[] score = new int[9];

        score[0] = Integer.parseInt(jtxtScore1.getText());
        score[1] = Integer.parseInt(jtxtScore2.getText());
        score[2] = Integer.parseInt(jtxtScore3.getText());
        score[3] = Integer.parseInt(jtxtScore4.getText());
        score[4] = Integer.parseInt(jtxtScore5.getText());
        score[5] = Integer.parseInt(jtxtScore6.getText());
        score[6] = Integer.parseInt(jtxtScore7.getText());
        score[7] = Integer.parseInt(jtxtScore8.getText());

        score[8] = score[0] + score[1] + score[2] + score[3] + score[4] + score[5] + score[6] + score[7];
        jtxtTotalScore.setText(Integer.toString(score[8]));

        if (score[8] >= 700) {
            jtxtRanking.setText("1st Class");

        } else if (score[8] >= 600) {
            jtxtRanking.setText("2i Class Upper");
        } else if (score[8] >= 500) {
            jtxtRanking.setText("2ii Class Lower");
        } else if (score[8] >= 400) {
            jtxtRanking.setText("3rd Class Lower");
        } else if (score[8] >= 300) {
            jtxtRanking.setText("CoHe");
        } else if (score[8] <= 299) {
            jtxtRanking.setText("Fail");
        }

        Calendar ToDay = Calendar.getInstance();
        ToDay.getTime();
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
        jtxtDate.setText(Tdate.format(ToDay.getTime()));

        if (score[0] > 100) {
            jtxtScore1.setText("0");
        }

        if (score[1] > 100) {
            jtxtScore2.setText("0");
        }

        if (score[2] > 100) {
            jtxtScore3.setText("0");
        }
        if (score[3] > 100) {
            jtxtScore4.setText("0");
        }
        if (score[4] > 100) {
            jtxtScore5.setText("0");
        }
        if (score[5] > 100) {
            jtxtScore6.setText("0");
        }
        if (score[6] > 100) {
            jtxtScore7.setText("0");
        }
        if (score[7] > 100) {
            jtxtScore8.setText("0");
        }

    }//GEN-LAST:event_jbtnResultActionPerformed

    private void jtxtScore8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScore8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScore8ActionPerformed

    private void jtxtScore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScore1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScore1ActionPerformed

    private void jtxtScore2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScore2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScore2ActionPerformed

    private void jtxtScore3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScore3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScore3ActionPerformed

    private void jtxtScore4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScore4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScore4ActionPerformed

    private void jtxtScore5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScore5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScore5ActionPerformed

    private void jtxtScore6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScore6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScore6ActionPerformed

    private void jtxtScore7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScore7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScore7ActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        // TODO add your handling code here:
        try {
            jtxtTranscript.print();
        } catch (java.awt.print.PrinterException e) {
            System.err.format("No Printer fountd", e.getMessage());
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit ", "Student Result System",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        JTextField jtxt = null;
        JComboBox jcbo = null;

        for (Component c : jPanel10.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                jtxt = (JTextField) c;
                jtxt.setText(null);
            }
        }

        for (Component c : jPanel7.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                jtxt = (JTextField) c;
                jtxt.setText(null);
            }
        }

        for (Component c : jPanel5.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                jtxt = (JTextField) c;
                jtxt.setText("0");
            }
        }

        for (Component c : jPanel5.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JComboBox")) {
                jcbo = (JComboBox) c;
                jcbo.setSelectedIndex(0);
            }
        }
        jtxtTranscript.setText(null);
        jcboGender.setSelectedIndex(0);
        jcboCourse.setSelectedIndex(0);
        jtxtTotalScore.setText("");
        jtxtRanking.setText("");
        jtxtDate.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTranscriptActionPerformed
        // TODO add your handling code here:
        jtxtTranscript.append("\t\t Transcript\n"
                + "======================================================\n"
                + "Stydent Registration Number:\t\t" + jtxtStudentID.getText() + "\n\n"
                + "Name: " + jtxtFirstname.getText() + "\t\t\t" + jtxtSurname.getText() + "\n\n"
                + "1: " + jcboModule1.getSelectedItem() + "\t\t\t" + jtxtScore1.getText() + "\n\n"
                + "2: " + jcboModule2.getSelectedItem() + "\t\t\t" + jtxtScore2.getText() + "\n\n"
                + "3: " + jcboModule3.getSelectedItem() + "\t\t\t" + jtxtScore3.getText() + "\n\n"
                + "4: " + jcboModule4.getSelectedItem() + "\t\t\t" + jtxtScore4.getText() + "\n\n"
                + "5: " + jcboModule5.getSelectedItem() + "\t\t\t" + jtxtScore5.getText() + "\n\n"
                + "6: " + jcboModule6.getSelectedItem() + "\t\t\t" + jtxtScore6.getText() + "\n\n"
                + "7: " + jcboModule7.getSelectedItem() + "\t\t\t" + jtxtScore7.getText() + "\n\n"
                + "8: " + jcboModule8.getSelectedItem() + "\t\t\t" + jtxtScore8.getText() + "\n\n"
                + "======================================================\n"
                + "Total Score: \t\t" + jtxtTotalScore.getText() + "\n"
                + "Ranking: \t\t" + jtxtRanking.getText() + "\n"
                + "Date: \t\t" + jtxtDate.getText() + "\n"
        );
    }//GEN-LAST:event_jbtnTranscriptActionPerformed

    private void jcboModule2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule2ActionPerformed
        if (jcboModule2.getSelectedItem().equals("")) {
            jtxtScore2.setText("0");
            jtxtScore2.setEnabled(false);

        } else {
            jtxtScore2.setText("");
            jtxtScore2.setEnabled(true);
            jtxtScore2.requestFocus();
        }
    }//GEN-LAST:event_jcboModule2ActionPerformed

    private void jcboModule1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule1ActionPerformed
        if (jcboModule1.getSelectedItem().equals("")) {
            jtxtScore1.setText("0");
            jtxtScore1.setEnabled(false);

        } else {
            jtxtScore1.setText("");
            jtxtScore1.setEnabled(true);
            jtxtScore1.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jcboModule1ActionPerformed

    private void jcboModule3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule3ActionPerformed
        if (jcboModule3.getSelectedItem().equals("")) {
            jtxtScore3.setText("0");
            jtxtScore3.setEnabled(false);

        } else {
            jtxtScore3.setText("");
            jtxtScore3.setEnabled(true);
            jtxtScore3.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jcboModule3ActionPerformed

    private void jcboModule4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule4ActionPerformed
        if (jcboModule4.getSelectedItem().equals("")) {
            jtxtScore4.setText("0");
            jtxtScore4.setEnabled(false);

        } else {
            jtxtScore4.setText("");
            jtxtScore4.setEnabled(true);
            jtxtScore4.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jcboModule4ActionPerformed

    private void jcboModule5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule5ActionPerformed
        if (jcboModule5.getSelectedItem().equals("")) {
            jtxtScore5.setText("0");
            jtxtScore5.setEnabled(false);

        } else {
            jtxtScore5.setText("");
            jtxtScore5.setEnabled(true);
            jtxtScore5.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jcboModule5ActionPerformed

    private void jcboModule6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule6ActionPerformed
        if (jcboModule6.getSelectedItem().equals("")) {
            jtxtScore6.setText("0");
            jtxtScore6.setEnabled(false);

        } else {
            jtxtScore6.setText("");
            jtxtScore6.setEnabled(true);
            jtxtScore6.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jcboModule6ActionPerformed

    private void jcboModule7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule7ActionPerformed
        if (jcboModule7.getSelectedItem().equals("")) {
            jtxtScore7.setText("0");
            jtxtScore7.setEnabled(false);

        } else {
            jtxtScore7.setText("");
            jtxtScore7.setEnabled(true);
            jtxtScore7.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jcboModule7ActionPerformed

    private void jcboModule8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule8ActionPerformed
        if (jcboModule8.getSelectedItem().equals("")) {
            jtxtScore8.setText("0");
            jtxtScore8.setEnabled(false);

        } else {
            jtxtScore8.setText("");
            jtxtScore8.setEnabled(true);
            jtxtScore8.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jcboModule8ActionPerformed

    private void jcboCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboCourseActionPerformed
        if (jcboCourse.getSelectedItem().equals("BA Animation")) {
            jtxtCourseC.setText("BA0895");
            jtxtFacultyN.setText("School of Art");
            jtxtDeanFac.setText("Prof. Daniel Moorehouse");
            jtxtCourseTutor.setText("Dr. Kerry Casey");
            jtxtProgL1.setText("Prof. Daniel Moorehouse");

        } else if (jcboCourse.getSelectedItem().equals("BSc Serious Games")) {
            jtxtCourseC.setText("BASc001");
            jtxtFacultyN.setText("School of Computer Games");
            jtxtDeanFac.setText("Prof. Tonio Montano");
            jtxtCourseTutor.setText("Dr. Carl Jhonson");
            jtxtProgL1.setText("Prof. Tomy Verceti");

        } else if (jcboCourse.getSelectedItem().equals("BSc Computer Science")) {
            jtxtCourseC.setText("BScC709");
            jtxtFacultyN.setText("School of Computer Science");
            jtxtDeanFac.setText("Prof. Ratatoi");
            jtxtCourseTutor.setText("Dr. Big Smoke");
            jtxtProgL1.setText("Prof. Sweet");
        } else if (jcboCourse.getSelectedItem().equals("BSc Computing")) {
            jtxtCourseC.setText("BScC025");
            jtxtFacultyN.setText("School of Computer Science");
            jtxtDeanFac.setText("Prof. Ratatoi");
            jtxtCourseTutor.setText("Dr. Big Smoke");
            jtxtProgL1.setText("Prof. Sweet");
        } else if (jcboCourse.getSelectedItem().equals("BSc Computer Animation")) {
            jtxtCourseC.setText("BScCA976");
            jtxtFacultyN.setText("School of Computer Science");
            jtxtDeanFac.setText("Prof. Ratatoi");
            jtxtCourseTutor.setText("Dr. Big Smoke");
            jtxtProgL1.setText("Prof. Sweet");
        } else if (jcboCourse.getSelectedItem().equals("BSc Information System")) {
            jtxtCourseC.setText("BScCA999");
            jtxtFacultyN.setText("School of Computer Science");
            jtxtDeanFac.setText("Prof. Ratatoi");
            jtxtCourseTutor.setText("Dr. Big Smoke");
            jtxtProgL1.setText("Prof. Sweet");
        } else if (jcboCourse.getSelectedItem().equals("Select a Course")) {
            JTextField jtxt = null;
            for (Component c : jPanel7.getComponents()) {
                if (c.getClass().toString().contains("javax.swing.JTextField")) {
                    jtxt = (JTextField) c;
                    jtxt.setText(null);
                }
            }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jcboCourseActionPerformed

    private void jtxtCourseTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCourseTutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCourseTutorActionPerformed

    private void jbtnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddNewActionPerformed
        try {

            Class.forName("com.mysql.jdbc.Driver");
            sqlCon = DriverManager.getConnection(dataCon, username, password);
            pst = sqlCon.prepareStatement("insert into studentresultdb(StudentID, Firstname, Surname,Address, Gender," + "DOB, Mobile, Email, Course, CourseCode,"
                    + "Module1,Module2,Module3,Module4,Module5,Module5,Module6,Module7,Module8,"
                    + "Score1, Score2,Score3,Score4,Score5,Score6,Score7,Score8,TotalScore,Ranking,Date)"
                    + "value(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, jtxtStudentID.getText());
            pst.setString(2, jtxtFirstname.getText());
            pst.setString(3, jtxtSurname.getText());
            pst.setString(4, jtxtAddre.getText());
            pst.setString(5, (String) jcboGender.getSelectedItem());
            pst.setString(6, jtxtDOB.getText());
            pst.setString(7, jtxtMobile.getText());
            pst.setString(8, jtxtEmail.getText());
            pst.setString(9, (String) jcboCourse.getSelectedItem());
            pst.setString(10, jtxtEmail.getText());

            pst.setString(11, (String) jcboModule1.getSelectedItem());
            pst.setString(12, (String) jcboModule2.getSelectedItem());
            pst.setString(13, (String) jcboModule3.getSelectedItem());
            pst.setString(14, (String) jcboModule4.getSelectedItem());
            pst.setString(15, (String) jcboModule5.getSelectedItem());
            pst.setString(16, (String) jcboModule6.getSelectedItem());
            pst.setString(17, (String) jcboModule7.getSelectedItem());
            pst.setString(18, (String) jcboModule8.getSelectedItem());

            pst.setString(19, (String) jtxtScore1.getText());
            pst.setString(20, (String) jtxtScore2.getText());
            pst.setString(21, (String) jtxtScore3.getText());
            pst.setString(22, (String) jtxtScore4.getText());
            pst.setString(23, (String) jtxtScore5.getText());
            pst.setString(24, (String) jtxtScore6.getText());
            pst.setString(25, (String) jtxtScore7.getText());
            pst.setString(26, (String) jtxtScore8.getText());

            pst.setString(27, (String) jtxtTotalScore.getText());
            pst.setString(28, (String) jtxtRanking.getText());
            pst.setString(29, (String) jtxtDate.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Student Result Updated");
            uploadDB();

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentResultSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(StudentResultSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_jbtnAddNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentResultSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentResultSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentResultSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentResultSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentResultSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel101;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAddNew;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnResult;
    private javax.swing.JButton jbtnTranscript;
    private javax.swing.JComboBox<String> jcboCourse;
    private javax.swing.JComboBox<String> jcboGender;
    private javax.swing.JComboBox<String> jcboModule1;
    private javax.swing.JComboBox<String> jcboModule2;
    private javax.swing.JComboBox<String> jcboModule3;
    private javax.swing.JComboBox<String> jcboModule4;
    private javax.swing.JComboBox<String> jcboModule5;
    private javax.swing.JComboBox<String> jcboModule6;
    private javax.swing.JComboBox<String> jcboModule7;
    private javax.swing.JComboBox<String> jcboModule8;
    private javax.swing.JTextField jtxtAddre;
    private javax.swing.JTextField jtxtCourseC;
    private javax.swing.JTextField jtxtCourseTutor;
    private javax.swing.JTextField jtxtDOB;
    private javax.swing.JTextField jtxtDate;
    private javax.swing.JTextField jtxtDeanFac;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtFacultyN;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtMobile;
    private javax.swing.JTextField jtxtProgL1;
    private javax.swing.JTextField jtxtRanking;
    private javax.swing.JTextField jtxtScore1;
    private javax.swing.JTextField jtxtScore2;
    private javax.swing.JTextField jtxtScore3;
    private javax.swing.JTextField jtxtScore4;
    private javax.swing.JTextField jtxtScore5;
    private javax.swing.JTextField jtxtScore6;
    private javax.swing.JTextField jtxtScore7;
    private javax.swing.JTextField jtxtScore8;
    private javax.swing.JTextField jtxtStudentID;
    private javax.swing.JTextField jtxtSurname;
    private javax.swing.JTextField jtxtTotalScore;
    private javax.swing.JTextArea jtxtTranscript;
    // End of variables declaration//GEN-END:variables
}
